commands:
  N98\Magento\Command\Installer\InstallCommand:
    installation:
      defaults:
        currency: USD
        admin_username: magecore
        admin_firstname: Firstname
        admin_lastname: Lastname
        admin_password: magecore2016
        admin_email: defaultemail@example.com
        locale: en_US
        timezone: Israel
    magento-packages:
      - name: magecorelab-magento-ee-1.14
        version: 1.14
        source:
          url: git@github.com:magecorelab/magento-ee.git
          type: git
          reference: 1.14
        extra:
          sample-data: sample-data-1.1.2
      - name: magecorelab-magento-ee-1.12
        version: 1.12
        source:
          url: git@github.com:magecorelab/magento-ee.git
          type: git
          reference: 1.12
        extra:
          sample-data: sample-data-1.1.2