commands:
  N98\Magento\Command\Installer\InstallCommand:
    installation:
      defaults:
        currency: USD
        admin_username: magecore
        admin_firstname: Firstname
        admin_lastname: Lastname
        admin_password: magecore2016
        admin_email: defaultemail@example.com